### PR TITLE
Fix iOS setItem

### LINKED ISSUE #112: setItem is broken in iOS in v2.3.0
Calling `setItem` with any value (object, array, string) in iOS causes error code 3.

e.g. 
```javascript
setItem('AnyKey', 'Any Value').catch(err => {/* err has code "3" (NULL_REFERENCE) */})
```

I believe the condition to check for a null reference [here](https://github.com/TheCocoaProject/cordova-plugin-nativestorage/blob/ed3e0d5775f904671e325988562eb74892476234/src/ios/NativeStorage.m#L214) is backwards.

I've opened a PR (#113) that addresses this issue. With this change, `setItem` works as expected.

### PR DESCRIPTION
**Pull request by beaulac**
Fixes #112

Corrects the null reference check for items being set.

~~Also separates the error messages to make it clearer what is null (key or value).~~
Retains the original behaviour of returning an error with int code `3` when either key or value is null.

### CODE REVIEW

File: src/ios/NativeStorage.m [hunk 1]
```diff
@@ -211,19 +211,23 @@ - (void) setItem: (CDVInvokedUrlCommand*) command
 		NSString* reference = [command.arguments objectAtIndex:0];
 		NSString* aString = [command.arguments objectAtIndex:1];
 
-		if(reference!=nil && [aString class] == [NSNull class])
+		if(reference==nil)
+		{
+			pluginResult = [CDVPluginResult resultWithStatus: CDVCommandStatus_ERROR messageAsString:@"Reference was null"];
```
Comment (pharos42) [inline src/ios/NativeStorage.m]: I think introducing messageAsString here is a breaking change as the original behavior for a nil reference was the messageAsInt.
I think it makes more sense to just change the '==' to '!=' on the null check of the original code to match the intended behavior.
If you flip the logic like you did here then 
```
if(reference==nil || [aString class] == [NSNull class])
{
pluginResult = [CDVPluginResult resultWithStatus: CDVCommandStatus_ERROR messageAsInt:3];
}
else ...
```

Comment (beaulac) [reply src/ios/NativeStorage.m]: Fair enough; I'll keep it as an int error code. 

IMO, it would be beneficial to introduce a separate code or message to indicate specifically which parameter was null.

**Comment by emrahcetiner** [comment]
when this fix will merge?
